services:
  postgres:
    image: postgres:16-alpine
    container_name: cms_postgres
    environment:
      POSTGRES_USER: jpastor
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cms_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U jpastor -d cms_db",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: cms_Adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    networks:
      - cms_network
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: cms_backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: jpastor
      POSTGRES_PASSWORD: "123"
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cms_db
      DATABASE_URL: postgresql+asyncpg://jpastor:123@postgres:5432/cms_db
      SECRET_KEY: super-secret-jwt-key-change-in-production
    networks:
      - cms_network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: cms_frontend
    ports:
      - "5173:5173"
    networks:
      - cms_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  cms_network:
    driver: bridge
