name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Tests and Generate Coverage
        run: |
          sudo mkdir -p /app/uploads
          sudo chown -R $USER:$USER /app
          
          pip install -r apps/api/requirements.txt
          export PYTHONPATH=$PYTHONPATH:$(pwd)/apps/api:$(pwd)
          pytest apps/api/tests/ --cov=apps/api/app --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        with:
          args: >
            "-Dsonar.projectKey=Moises-Mestas_All-In-One"
            "-Dsonar.organization=moises-mestas"
            "-Dsonar.python.coverage.reportPaths=coverage.xml" 
            "-Dsonar.coverage.exclusions=apps/web/**"
            "-Dsonar.cpd.exclusions=apps/web/src/pages/webEditor/editorBlocks.ts"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}